artifact_uri: file:///home/mle-user/mle_projects/mle-mlflow/mlflow_experiments_store/0/c0ed4383ea324e4ab422768a166149d3/artifacts
end_time: 1710888281350
entry_point_name: ''
experiment_id: '0'
lifecycle_stage: active
run_id: c0ed4383ea324e4ab422768a166149d3
run_name: Default
run_uuid: c0ed4383ea324e4ab422768a166149d3
source_name: ''
source_type: 4
source_version: ''
start_time: 1710888281336
status: 3
tags: []
user_id: mle-user
