artifact_uri: file:///home/mle-user/mle_projects/mle-mlflow/mlflow_experiments_store/0/0f8d127a04b04ed69027f8d7906acfd8/artifacts
end_time: 1710952689279
entry_point_name: ''
experiment_id: '0'
lifecycle_stage: active
run_id: 0f8d127a04b04ed69027f8d7906acfd8
run_name: Default
run_uuid: 0f8d127a04b04ed69027f8d7906acfd8
source_name: ''
source_type: 4
source_version: ''
start_time: 1710952689259
status: 3
tags: []
user_id: mle-user
