artifact_uri: file:///home/mle-user/mle_projects/mle-mlflow/mlflow_experiments_store/0/ae6b035a73ca4dd2b28cc02c780a4850/artifacts
end_time: 1710887793957
entry_point_name: ''
experiment_id: '0'
lifecycle_stage: active
run_id: ae6b035a73ca4dd2b28cc02c780a4850
run_name: Default
run_uuid: ae6b035a73ca4dd2b28cc02c780a4850
source_name: ''
source_type: 4
source_version: ''
start_time: 1710887793946
status: 3
tags: []
user_id: mle-user
