artifact_uri: file:///home/mle-user/mle_projects/mle-mlflow/mlflow_experiments_store/0/8f649b5eb5564fa081cbc264b57d29c8/artifacts
end_time: 1710952681024
entry_point_name: ''
experiment_id: '0'
lifecycle_stage: active
run_id: 8f649b5eb5564fa081cbc264b57d29c8
run_name: Default
run_uuid: 8f649b5eb5564fa081cbc264b57d29c8
source_name: ''
source_type: 4
source_version: ''
start_time: 1710952680848
status: 3
tags: []
user_id: mle-user
