artifact_uri: file:///home/mle-user/mle_projects/mle-mlflow/mlflow_experiments_store/0/f3e468b55466406c8514348185b276c5/artifacts
end_time: 1710888235500
entry_point_name: ''
experiment_id: '0'
lifecycle_stage: active
run_id: f3e468b55466406c8514348185b276c5
run_name: Default
run_uuid: f3e468b55466406c8514348185b276c5
source_name: ''
source_type: 4
source_version: ''
start_time: 1710888235487
status: 3
tags: []
user_id: mle-user
