artifact_uri: file:///home/mle-user/mle_projects/mle-mlflow/mlflow_experiments_store/0/1eb6150f365040f7ac7dcc80ff2bec8a/artifacts
end_time: 1710953295456
entry_point_name: ''
experiment_id: '0'
lifecycle_stage: active
run_id: 1eb6150f365040f7ac7dcc80ff2bec8a
run_name: Default
run_uuid: 1eb6150f365040f7ac7dcc80ff2bec8a
source_name: ''
source_type: 4
source_version: ''
start_time: 1710953295425
status: 3
tags: []
user_id: mle-user
