artifact_uri: file:///home/mle-user/mle_projects/mle-mlflow/mlflow_experiments_store/0/c5d99e73b9e244ec9ce993a0a9d503a9/artifacts
end_time: 1710888231325
entry_point_name: ''
experiment_id: '0'
lifecycle_stage: active
run_id: c5d99e73b9e244ec9ce993a0a9d503a9
run_name: Default
run_uuid: c5d99e73b9e244ec9ce993a0a9d503a9
source_name: ''
source_type: 4
source_version: ''
start_time: 1710888231307
status: 3
tags: []
user_id: mle-user
