artifact_uri: file:///home/mle-user/mle_projects/mle-mlflow/mlflow_experiments_store/0/cfd2a4d05e22445089bc32959ccb23de/artifacts
end_time: 1710888170410
entry_point_name: ''
experiment_id: '0'
lifecycle_stage: active
run_id: cfd2a4d05e22445089bc32959ccb23de
run_name: Default
run_uuid: cfd2a4d05e22445089bc32959ccb23de
source_name: ''
source_type: 4
source_version: ''
start_time: 1710888170396
status: 3
tags: []
user_id: mle-user
