artifact_uri: file:///home/mle-user/mle_projects/mle-mlflow/mlflow_experiments_store/0/f5cc10bfe2d6455692fb1272cb7cc0d0/artifacts
end_time: 1710952686912
entry_point_name: ''
experiment_id: '0'
lifecycle_stage: active
run_id: f5cc10bfe2d6455692fb1272cb7cc0d0
run_name: Default
run_uuid: f5cc10bfe2d6455692fb1272cb7cc0d0
source_name: ''
source_type: 4
source_version: ''
start_time: 1710952686898
status: 3
tags: []
user_id: mle-user
