artifact_uri: file:///home/mle-user/mle_projects/mle-mlflow/mlflow_experiments_store/0/dca1bdc661fc4a2b870daa80982be381/artifacts
end_time: 1710952948181
entry_point_name: ''
experiment_id: '0'
lifecycle_stage: active
run_id: dca1bdc661fc4a2b870daa80982be381
run_name: Default
run_uuid: dca1bdc661fc4a2b870daa80982be381
source_name: ''
source_type: 4
source_version: ''
start_time: 1710952948165
status: 3
tags: []
user_id: mle-user
