artifact_uri: file:///home/mle-user/mle_projects/mle-mlflow/mlflow_experiments_store/0/dc07fcae312d4dbd89dbbcac0df00442/artifacts
end_time: 1710954059487
entry_point_name: ''
experiment_id: '0'
lifecycle_stage: active
run_id: dc07fcae312d4dbd89dbbcac0df00442
run_name: Default
run_uuid: dc07fcae312d4dbd89dbbcac0df00442
source_name: ''
source_type: 4
source_version: ''
start_time: 1710954059471
status: 3
tags: []
user_id: mle-user
